# 公共配置文件
# @author xuanyue18

server:
  port: 8121
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: xoj-backend
  profiles:
    active: prod
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${xuanyue.datasource.url}
    username: ${xuanyue.datasource.username}
    password: ${xuanyue.datasource.password}
  # Redis 配置
  redis:
    database: ${xuanyue.redis.database}
    host: ${xuanyue.redis.host}
    port: ${xuanyue.redis.port}
    timeout: ${xuanyue.redis.timeout}
  #    password: ${xuanyue.redis.password}
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: ${xuanyue.mybatis-plus.log-impl}
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx




# 对象存储
# todo 腾讯云对象存储
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# todo 阿里云对象存储
aliyun:
  oss:
    file:
      endpoint: ${xuanyue.aliyun.oss.file.endpoint}
      access_key: ${xuanyue.aliyun.oss.file.access_key}
      secret_key: ${xuanyue.aliyun.oss.file.secret_key}
      bucket_name: ${xuanyue.aliyun.oss.file.bucket_name}

# jwt 配置
xoj:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xuanyue18
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: xuanyue18
    user-ttl: 72000000
    user-token-name: Authentication

# 代码沙箱配置
codesandbox:
  type: remote
